name: Docker Image CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t emvee/ksafrontend .
    - name: Push the Docker image
      run: docker login -u emvee -p ${{ secrets.DOCKER_TOKEN }} && docker push emvee/ksafrontend:latest